foreground   #e7ddd2
background   #0C1213
cursor       #e7ddd2

color0       #0C1213
color8       #a19a93
color1       #78823F
color9       #78823F
color2       #788560
color10      #788560
color3       #988F71
color11      #988F71
color4       #CF9B71
color12      #CF9B71
color5       #BA6E85
color13      #BA6E85
color6       #BBA692
color14      #BBA692
color7       #e7ddd2
color15      #e7ddd2
